export const CONTAINS = Object.freeze({
  ALERTS: 'Alerts',
  NEWALERTS: 'New Alerts',
  USERS: 'Users',
  SMS: 'Sms',
  SMS_DETAILS: 'Sms Details',
  SCHEDULED_SMS: 'Scheduled Sms',
  NOTIFICATION: 'notifications',
  EMAIL: 'Email',
  EMAILS: 'Emails',
  EMAILS_DETAILS: 'Emails Details',
  SCHEDULED_EMAILS: 'Scheduled Emails',
  SCHEDULED_NOTIFICATION: 'Scheduled Notification',
  SAVE: 'Save',
  CANCEL: 'Cancel',
  PUSH: 'push',
  ACCOUNTINFO: 'Account Info',
  DASHBOARD: 'Dashboard',
  SUBSCRIBER: 'Subscriber',
  APPLICATIONS: 'Applications',
  ORGANIZATIONS: 'Organizations',
  ADD_ORGANIZATIONS: 'Add Organizations',
  ADD_SUBSCRIBER: 'Add Subscriber',
  NEW_USER: 'New User',
  ADD_USER: 'Add User',
  ADMIN_USER: 'admin-users',
  ADMIN_APPLICATION: 'admin-application',
  ADMIN_ORGANIZATIONS: 'admin-organizations',
  PUSHNOTIFICATIONS: 'Push Notifications',
  PUSHNOTIFICATIONS_DETAILS: 'Push Notifications Details',
  SCHEDULED_PUSHNOTIFICATIONS: 'Scheduled Push Notifications',
  SUBMIT: 'Submit',
  SUCCESS: 'Success',
  ERROR: 'Error',
  SWW: 'Something went wronge.',
  CONFIGURE_SERVICE: 'Configure Service',
  SERVICES: 'Services',
  VIEW: 'View',
  MAIL: 'MAIL',
  SIGNOUT: 'Sign Out',
  CONFIGURE_SMS_SERVICE: 'Configure SMS Service',
  CONFIGURE_PUSH_SERVICE: 'Configure Push Notification Service',
  CONFIGURE_EMAIL_SERVICE: 'Configure Email Service',
  CONFIBUTTON: 'ConfigButton',
  SIGNOUTBUTTON: 'SignOutButton',
  ADD_YOUR_LOGO: 'Add your logo',
  ADMIN_ALERTS: 'admin-alerts',
  ISEMAILSERVICE: 'isEmailService',
  ISSMSSERVICE: 'isSmsService',
  ISPUSHSERVICE: 'isPushService',
  REGISTER: 'Register',
  ADD_APPLICATIONS: 'Add Applications',
  EDIT_USER: 'Edit User',
  APPLICATION: 'Application',
});
